# .github/workflows/deploy-nanoapi.yml

name: nanoapi_build_and_deploy

on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Build and deploy via Nano API
        uses: Nano-API/Deploy@version/0
        with:
            apiKey: ${{ secrets.NANO_API_TOKEN }} # Your Nano API token, stored in Github secrets
            buildConfigId: '66e460860fcd4e7d65791176'
            commitSha: ${{ github.sha }}